version: "3.8"

services:
  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - type: bind
        source: "D:/omero_db"
        target: "/var/lib/postgresql/data"

  omeroserver:
    image: "openmicroscopy/omero-server:5.6"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero@volker_370
      CONFIG_omero_db_name: omero
      ROOTPASS: omero@volker_370
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - type: bind
        source: "D:/omero_files"
        target: "/OMERO"

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5.6"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"

networks:
  omero:
