version: "3.8"

services:
  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero@volker_370
    networks:
      - omero
    user: postgres
    volumes:
      - omero_postgres_db:/var/lib/postgresql/data

  omeroserver:
    image: "openmicroscopy/omero-server:5.6.2"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: postgres
      CONFIG_omero_db_pass: omero@volker_370
      CONFIG_omero_db_name: omero
      ROOTPASS: omero@volker_370
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - /home/vagrant/data:/OMERO

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5.6.2"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"

networks:
  omero:

volumes:
  omero_postgres_db:
